# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        public.storage:
            adapter: 'local'
            options:
                directory: '%public_storage_path%'