parameters:
    app_name: 'Backoffice'
    from_mail: 'noreply@domain.tld'
    locale: 'pt'
    public_storage_path: '%kernel.project_dir%/public/storage'
    images_path: 'images' # relative to the public storage