parameters:
    app.name: 'Backoffice'

twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%app_name%'
    form_themes:
        - 'form/image_type.html.twig'
        - 'bootstrap_4_layout.html.twig'
